services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app