CREATE DATABASE IF NOT EXISTS game;
USE game;

CREATE TABLE IF NOT EXISTS users (
    userID INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(50) NOT NULL,
    active TINYINT(1) DEFAULT 1
);

INSERT INTO users VALUES (1, 'test', 'test@test.com', 'a94a8fe5ccb19ba61c4c0873d391e987982fbbd3');

GRANT ALL PRIVILEGES ON game.* TO 'admin'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;